name: Build HoloKernel

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install cross-compiler toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential nasm qemu-system-i386 gcc-multilib
        
        # Build i686-elf cross-compiler from source using a simpler approach
        # Install dependencies for building cross-compiler
        sudo apt-get install -y wget make libgmp3-dev libmpfr-dev libmpc-dev flex bison
        
        # Create temporary directory
        mkdir -p /tmp/cross-compiler
        cd /tmp/cross-compiler
        
        # Download and build binutils
        wget https://ftp.gnu.org/gnu/binutils/binutils-2.40.tar.xz
        tar -xf binutils-2.40.tar.xz
        mkdir binutils-build
        cd binutils-build
        ../binutils-2.40/configure --target=i686-elf --prefix=/usr/local --disable-nls --disable-werror
        make -j$(nproc)
        sudo make install
        
        # Download and build gcc (minimal for kernel development)
        cd /tmp/cross-compiler
        wget https://ftp.gnu.org/gnu/gcc/gcc-12.2.0/gcc-12.2.0.tar.xz
        tar -xf gcc-12.2.0.tar.xz
        mkdir gcc-build
        cd gcc-build
        ../gcc-12.2.0/configure --target=i686-elf --prefix=/usr/local --disable-nls --enable-languages=c --without-headers
        make -j$(nproc) all-gcc all-target-libgcc
        sudo make install-gcc install-target-libgcc
        
        # Verify installation
        /usr/local/bin/i686-elf-gcc --version
    
    - name: Build kernel
      run: |
        make clean
        make all
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: holokernel-build
        path: |
          kernel.bin
          disk.img
          *.o
